export const allCards:any = [
    {
      id:0,
      name:"../../assets/images/heart.png",
      isSelected:false
    },
    {
      id:1,
      name:"../../assets/images/heart.png",
      isSelected:false
    },
    {
      id:2,
      name:"../../assets/images/square.png",
      isSelected:false
    },
    {
      id:3,
      name:"../../assets/images/square.png",
      isSelected:false
    },
    {
      id:4,
      name:"../../assets/images/spade.png",
      isSelected:false
    },
    {
      id:5,
      name:"../../assets/images/spade.png",
      isSelected:false
    },
  ];